name = "shopper-s-suggestions-telegram"
main = "telegram-worker.js"
compatibility_date = "2026-09-19"

[[d1_databases]]
binding = "DB"
database_name = "product-db"
database_id = "7fc3ac99-20b3-40f1-a022-1a11a0b4a177"

[vars]
GITHUB_BRANCH = "main"
GITHUB_OWNER = "shop-now-with"
GITHUB_REPO = "Shopper-s-suggestions"
TELEGRAM_FEEDBACK_CHAT_ID = "8822043643"
TELEGRAM_GROUP_IDS = "-1003414319140"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true

